title: Yunong Li's Homepage
page-top-title: Yunong Li
top-section-bg-text: Mechanism Theory & Origami Engineering
home-subtitle: Yunong Li&ensp;|&ensp;李雨浓
copyright-text: '&copy; Yunong Li 2025. All Rights Reserved.'
github-link: <a href="https://github.com/Ramon-LYN">Github</a>
license-link: <a href="https://github.com/Ramon-LYN/ramon-lyn.github.io/blob/main/LICENSE">License</a>
